version: '3.8'

services:
  backend:
    build: 
      context: ..
      dockerfile: deploy/Dockerfile.backend
    container_name: doclibbackend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=DocumentLibrary;User=sa;Password=YourPassword123;
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    container_name: doclibfrontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: doclibdatabase
    environment:
      SA_PASSWORD: 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
